import Foundation

/// Die Keks-Fragen (lokal, Deutsch). Pro Tag eine, für beide dieselbe: Index aus dem Datum.
enum ZimmerRitualeFragen {
    static let alle: [String] = [
        "Was war heute das Schönste für dich?",
        "Welches Essen sollen wir unbedingt zusammen kochen?",
        "Woran denkst du, wenn du an uns denkst?",
        "Welcher Ort soll unser nächster Ausflug sein?",
        "Was hat dich heute zum Lächeln gebracht?",
        "Welches Lied erinnert dich an mich?",
        "Was ist dein liebster Moment mit mir?",
        "Welche Kleinigkeit macht dich sofort glücklich?",
        "Was möchtest du mit mir einmal ausprobieren?",
        "Wie sieht für dich ein perfekter fauler Sonntag aus?",
        "Was magst du an unseren Abenden am meisten?",
        "Welche Eissorte bin ich?",
        "Wenn wir ein Tier adoptieren würden, welches?",
        "Was war dein erster Gedanke, als du mich gesehen hast?",
        "Welchen Film könnten wir hundertmal schauen?",
        "Was wünschst du dir für uns im nächsten Jahr?",
        "Welches kleine Ritual von uns magst du am liebsten?",
        "Was würdest du mir gern mal kochen?",
        "Wohin würdest du mit mir spontan fliegen?",
        "Was gibt dir Kraft an schweren Tagen?",
        "Welche Eigenschaft an mir magst du am meisten?",
        "Was war das lustigste, das wir zusammen erlebt haben?",
        "Welches Geschenk hat dich am meisten gefreut?",
        "Was sollen wir in zehn Jahren immer noch tun?",
        "Welchen Geruch verbindest du mit Zuhause?",
        "Was ist dein Lieblingsplatz in unserer Stadt?",
        "Welche Umarmung war die beste?",
        "Was würdest du an einem freien Tag mit mir machen?",
        "Welches Wort beschreibt uns am besten?",
        "Was hast du von mir gelernt?",
        "Welche Jahreszeit passt am besten zu uns?",
        "Was ist dein liebstes Foto von uns?",
        "Worauf freust du dich diese Woche?",
        "Welche Süßigkeit soll ich dir mitbringen?",
        "Was würdest du einer kleinen Version von uns sagen?",
        "Welches Spiel sollen wir zusammen zocken?",
        "Was macht dich an mir sprachlos?",
        "Welchen Superhelden-Namen hätten wir als Paar?",
        "Was war dein bester Tag diesen Monat?",
        "Wie klingt für dich ein gemütlicher Abend?",
        "Welcher Duft erinnert dich an uns?",
        "Was würdest du gern öfter mit mir teilen?",
        "Welches Café sollen wir als Nächstes testen?",
        "Was bringt dich zum Lachen, egal wie müde du bist?",
        "Wenn wir ein Haus hätten, was dürfte nie fehlen?",
        "Was war die schönste Nachricht der letzten Zeit?",
        "Welche Farbe hat dein heutiger Tag?",
        "Was möchtest du heute von mir hören?",
        "Welche Serie sollen wir zusammen anfangen?",
        "Was ist dein Lieblingsgeräusch am Morgen?",
        "Welches Abenteuer wartet noch auf uns?",
        "Was an uns macht dich stolz?",
        "Welche Kleinigkeit soll ich öfter für dich tun?",
        "Was war dein liebster Kinderspielplatz?",
        "Welches Frühstück macht dich glücklich?",
        "Was würdest du mit mir im Regen machen?",
        "Welche Erinnerung an uns wärmt dich am meisten?",
        "Was wünschst du dir heute Abend?",
        "Welchen Spitznamen magst du am liebsten?",
        "Was wollen wir uns für den Winter vornehmen?",
        "Wofür bist du heute dankbar?",
        "Was würdest du mir gern ins Ohr flüstern?"
    ]

    static func frage(tag: String) -> String {
        alle[ZimmerRitualeLogik.fragenIndex(tag: tag, anzahl: alle.count)]
    }
}
