// Generated by design/figur-redesign/swift_export.py from ahmed-B.svg and annika-3.svg. Do not edit by hand:
// change bau.py, run `python bau.py && python swift_export.py`.
// Coordinates are the 200 x 240 half-figure space of FigurView. Colours and gradients live in FigurView.

import SwiftUI

/// Ahmed, face option B ("Bitmoji modern schlank"). Draw order and colours: FigurView `neuesGesichtB`.
enum GesichtB {
    static var haarHinten: Path {
        Path { p in
            p.move(to: P(51, 82))
            p.addQuadCurve(to: P(46, 70), control: P(43.2, 77.7))
            p.addQuadCurve(to: P(45, 56), control: P(37.9, 63.4))
            p.addQuadCurve(to: P(50, 42), control: P(38.1, 47))
            p.addQuadCurve(to: P(59, 31), control: P(49.5, 33.9))
            p.addQuadCurve(to: P(71, 23), control: P(59.5, 21.8))
            p.addQuadCurve(to: P(86, 18), control: P(73.9, 12.1))
            p.addQuadCurve(to: P(102, 16), control: P(93.2, 11.5))
            p.addQuadCurve(to: P(118, 18), control: P(111.7, 9.6))
            p.addQuadCurve(to: P(132, 23), control: P(130.1, 12.4))
            p.addQuadCurve(to: P(144, 32), control: P(142.3, 23.9))
            p.addQuadCurve(to: P(151, 44), control: P(154.4, 34.8))
            p.addQuadCurve(to: P(155, 58), control: P(162.5, 49.4))
            p.addQuadCurve(to: P(154, 71), control: P(160.1, 65))
            p.addQuadCurve(to: P(149, 82), control: P(158.7, 78.8))
            p.addQuadCurve(to: P(150, 94), control: P(157.9, 92.7))
            p.addQuadCurve(to: P(50, 94), control: P(100, 99.6))
            p.addQuadCurve(to: P(51, 82), control: P(43.9, 91.7))
            p.closeSubpath()
        }
    }
    static var hals: Path {
        Path { p in
            p.move(to: P(88, 128))
            p.addLine(to: P(87, 176))
            p.addLine(to: P(113, 176))
            p.addLine(to: P(112, 128))
            p.closeSubpath()
        }
    }
    static var halsSchatten: Path {
        Path { p in
            p.move(to: P(80, 128))
            p.addLine(to: P(120, 128))
            p.addLine(to: P(120, 150))
            p.addQuadCurve(to: P(80, 150), control: P(100, 166))
            p.closeSubpath()
        }
    }
    static var ohrL: Path {
        Path { p in
            p.move(to: P(56, 93))
            p.addCurve(to: P(43, 107), control1: P(47, 87), control2: P(41, 97))
            p.addCurve(to: P(57, 117), control1: P(45, 116), control2: P(51, 121))
            p.closeSubpath()
        }
    }
    static var ohrR: Path {
        Path { p in
            p.move(to: P(144, 93))
            p.addCurve(to: P(157, 107), control1: P(153, 87), control2: P(159, 97))
            p.addCurve(to: P(143, 117), control1: P(155, 116), control2: P(149, 121))
            p.closeSubpath()
        }
    }
    static var ohrInnenL: Path {
        Path { p in
            p.move(to: P(52, 97))
            p.addCurve(to: P(52, 111), control1: P(47, 99), control2: P(47, 108))
        }
    }
    static var ohrInnenR: Path {
        Path { p in
            p.move(to: P(148, 97))
            p.addCurve(to: P(148, 111), control1: P(153, 99), control2: P(153, 108))
        }
    }
    static var gesicht: Path {
        Path { p in
            p.move(to: P(100, 26))
            p.addCurve(to: P(147, 77), control1: P(127, 26), control2: P(147, 44))
            p.addCurve(to: P(139, 129), control1: P(147, 100), control2: P(145, 117))
            p.addCurve(to: P(100, 151), control1: P(132, 142), control2: P(117, 150))
            p.addCurve(to: P(61, 129), control1: P(83, 150), control2: P(68, 142))
            p.addCurve(to: P(53, 77), control1: P(55, 117), control2: P(53, 100))
            p.addCurve(to: P(100, 26), control1: P(53, 44), control2: P(73, 26))
            p.closeSubpath()
        }
    }
    static var ponySchatten: Path {
        Path { p in
            p.move(to: P(51, 82))
            p.addQuadCurve(to: P(46, 70), control: P(40.9, 78.6))
            p.addQuadCurve(to: P(45, 56), control: P(37.5, 63.7))
            p.addQuadCurve(to: P(50, 42), control: P(39.6, 47.6))
            p.addQuadCurve(to: P(59, 31), control: P(47.3, 33.1))
            p.addQuadCurve(to: P(71, 23), control: P(59, 21.7))
            p.addQuadCurve(to: P(86, 18), control: P(74.5, 13.6))
            p.addQuadCurve(to: P(102, 16), control: P(92.8, 9.1))
            p.addQuadCurve(to: P(118, 18), control: P(111.9, 9.2))
            p.addQuadCurve(to: P(132, 23), control: P(129.4, 13.8))
            p.addQuadCurve(to: P(144, 32), control: P(144.2, 22.5))
            p.addQuadCurve(to: P(151, 44), control: P(154.9, 34.9))
            p.addQuadCurve(to: P(155, 58), control: P(160.9, 50))
            p.addQuadCurve(to: P(154, 71), control: P(162.4, 65.4))
            p.addQuadCurve(to: P(149, 82), control: P(159, 79.2))
            p.addQuadCurve(to: P(146, 86), control: P(154.5, 87.8))
            p.addQuadCurve(to: P(138, 90), control: P(148.5, 92.6))
            p.addQuadCurve(to: P(128, 84), control: P(139, 92.3))
            p.addQuadCurve(to: P(119, 87), control: P(128.7, 91.6))
            p.addQuadCurve(to: P(110, 79), control: P(118.5, 89.9))
            p.addQuadCurve(to: P(101, 82), control: P(107.4, 88.3))
            p.addQuadCurve(to: P(92, 75), control: P(95.2, 86.4))
            p.addQuadCurve(to: P(83, 78), control: P(83, 83.1))
            p.addQuadCurve(to: P(74, 73), control: P(72.3, 80.6))
            p.addQuadCurve(to: P(65, 77), control: P(62.5, 78.9))
            p.addQuadCurve(to: P(57, 79), control: P(53.9, 81.7))
            p.addQuadCurve(to: P(51, 82), control: P(46.8, 84))
            p.closeSubpath()
        }
    }
    static var wangeL: Path {
        oval(P(62, 122), 10, 15)
    }
    static var wangeR: Path {
        oval(P(138, 122), 10, 15)
    }
    static var taperL: Path {
        Path { p in
            p.move(to: P(47, 80))
            p.addCurve(to: P(51, 101), control1: P(46, 88), control2: P(47, 96))
            p.addLine(to: P(57, 100))
            p.addCurve(to: P(59, 81), control1: P(56, 94), control2: P(56, 87))
            p.closeSubpath()
        }
    }
    static var taperR: Path {
        Path { p in
            p.move(to: P(153, 80))
            p.addCurve(to: P(149, 101), control1: P(154, 88), control2: P(153, 96))
            p.addLine(to: P(143, 100))
            p.addCurve(to: P(141, 81), control1: P(144, 94), control2: P(144, 87))
            p.closeSubpath()
        }
    }
    static var kinnbart: Path {
        Path { p in
            p.move(to: P(96, 143))
            p.addQuadCurve(to: P(104, 143), control: P(100, 142))
            p.addQuadCurve(to: P(100, 148.5), control: P(103.5, 148))
            p.addQuadCurve(to: P(96, 143), control: P(96.5, 148))
            p.closeSubpath()
        }
    }
    static var kinnSchatten: Path {
        Path { p in
            p.move(to: P(86, 149))
            p.addQuadCurve(to: P(114, 149), control: P(100, 145))
            p.addLine(to: P(114, 158))
            p.addLine(to: P(86, 158))
            p.closeSubpath()
        }
    }
    static var augeWeissL: Path {
        Path { p in
            p.move(to: P(91, 102))
            p.addQuadCurve(to: P(70, 99.5), control: P(81, 88))
            p.addQuadCurve(to: P(91, 102), control: P(80, 110))
            p.closeSubpath()
        }
    }
    static var lidL: Path {
        Path { p in
            p.move(to: P(89, 92))
            p.addLine(to: P(72, 92))
            p.addLine(to: P(72, 99.5))
            p.addQuadCurve(to: P(89, 101.5), control: P(81, 93))
            p.closeSubpath()
        }
    }
    static var lidStrichL: Path {
        Path { p in
            p.move(to: P(91, 101.5))
            p.addQuadCurve(to: P(70, 99.5), control: P(81, 93))
        }
    }
    static var lidFalteL: Path {
        Path { p in
            p.move(to: P(89, 95.5))
            p.addQuadCurve(to: P(71, 96), control: P(81, 89))
        }
    }
    static var augeWeissR: Path {
        Path { p in
            p.move(to: P(109, 102))
            p.addQuadCurve(to: P(130, 99.5), control: P(119, 88))
            p.addQuadCurve(to: P(109, 102), control: P(120, 110))
            p.closeSubpath()
        }
    }
    static var lidR: Path {
        Path { p in
            p.move(to: P(107, 92))
            p.addLine(to: P(132, 92))
            p.addLine(to: P(132, 99.5))
            p.addQuadCurve(to: P(107, 101.5), control: P(119, 93))
            p.closeSubpath()
        }
    }
    static var lidStrichR: Path {
        Path { p in
            p.move(to: P(109, 101.5))
            p.addQuadCurve(to: P(130, 99.5), control: P(119, 93))
        }
    }
    static var lidFalteR: Path {
        Path { p in
            p.move(to: P(111, 95.5))
            p.addQuadCurve(to: P(129, 96), control: P(119, 89))
        }
    }
    static var lachLidL: Path {
        Path { p in
            p.move(to: P(69, 107))
            p.addQuadCurve(to: P(93, 106), control: P(81, 100))
            p.addLine(to: P(93, 115))
            p.addLine(to: P(69, 115))
            p.closeSubpath()
        }
    }
    static var lachLidStrichL: Path {
        Path { p in
            p.move(to: P(72, 106))
            p.addQuadCurve(to: P(90, 105.5), control: P(81, 101))
        }
    }
    static var lachLidR: Path {
        Path { p in
            p.move(to: P(107, 107))
            p.addQuadCurve(to: P(131, 106), control: P(119, 100))
            p.addLine(to: P(131, 115))
            p.addLine(to: P(107, 115))
            p.closeSubpath()
        }
    }
    static var lachLidStrichR: Path {
        Path { p in
            p.move(to: P(110, 106))
            p.addQuadCurve(to: P(128, 105.5), control: P(119, 101))
        }
    }
    static var braueL: Path {
        Path { p in
            p.move(to: P(92, 88.5))
            p.addQuadCurve(to: P(70, 86.5), control: P(81, 85))
        }
    }
    static var braueR: Path {
        Path { p in
            p.move(to: P(108, 88.5))
            p.addQuadCurve(to: P(130, 86.5), control: P(119, 85))
        }
    }
    static var nase: Path {
        Path { p in
            p.move(to: P(102, 103))
            p.addLine(to: P(104.5, 120))
            p.addQuadCurve(to: P(98, 123.5), control: P(103, 124.5))
        }
    }
    static var nasenSchatten: Path {
        oval(P(100, 125), 6, 2)
    }
    static var schnurrbart: Path {
        Path { p in
            p.move(to: P(100, 129.5))
            p.addCurve(to: P(84, 133.5), control1: P(95, 127.5), control2: P(88, 128))
            p.addCurve(to: P(100, 132.2), control1: P(89, 131), control2: P(95, 131.5))
            p.addCurve(to: P(116, 133.5), control1: P(105, 131.5), control2: P(111, 131))
            p.addCurve(to: P(100, 129.5), control1: P(112, 128), control2: P(105, 127.5))
            p.closeSubpath()
        }
    }
    static var lippeOben: Path {
        Path { p in
            p.move(to: P(90, 137.5))
            p.addQuadCurve(to: P(100, 136), control: P(95, 134.5))
            p.addQuadCurve(to: P(110, 137.5), control: P(105, 134.5))
            p.addQuadCurve(to: P(90, 137.5), control: P(100, 139))
            p.closeSubpath()
        }
    }
    static var lippeUnten: Path {
        Path { p in
            p.move(to: P(90, 137.5))
            p.addQuadCurve(to: P(110, 137.5), control: P(100, 139))
            p.addQuadCurve(to: P(100, 143.5), control: P(106, 143.5))
            p.addQuadCurve(to: P(90, 137.5), control: P(94, 143.5))
            p.closeSubpath()
        }
    }
    static var lachMund: Path {
        Path { p in
            p.move(to: P(88, 135.5))
            p.addQuadCurve(to: P(112, 135.5), control: P(100, 139))
            p.addQuadCurve(to: P(100, 146), control: P(109, 146))
            p.addQuadCurve(to: P(88, 135.5), control: P(91, 146))
            p.closeSubpath()
        }
    }
    static var lachZaehne: Path {
        Path { p in
            p.move(to: P(90, 136.5))
            p.addQuadCurve(to: P(110, 136.5), control: P(100, 139.5))
            p.addLine(to: P(109, 139))
            p.addQuadCurve(to: P(91, 139), control: P(100, 141.5))
            p.closeSubpath()
        }
    }
    static var lachZunge: Path {
        Path { p in
            p.move(to: P(94, 144))
            p.addQuadCurve(to: P(106, 144), control: P(100, 141.5))
            p.addQuadCurve(to: P(94, 144), control: P(100, 146.5))
            p.closeSubpath()
        }
    }
    static var haarVorn: Path {
        Path { p in
            p.move(to: P(51, 82))
            p.addQuadCurve(to: P(46, 70), control: P(42.5, 78.1))
            p.addQuadCurve(to: P(45, 56), control: P(37.1, 63.8))
            p.addQuadCurve(to: P(50, 42), control: P(37.2, 47.2))
            p.addQuadCurve(to: P(59, 31), control: P(48.7, 33.8))
            p.addQuadCurve(to: P(71, 23), control: P(58.7, 21.4))
            p.addQuadCurve(to: P(86, 18), control: P(73.3, 11.5))
            p.addQuadCurve(to: P(102, 16), control: P(93.1, 10.7))
            p.addQuadCurve(to: P(118, 18), control: P(112, 8.8))
            p.addQuadCurve(to: P(132, 23), control: P(130.8, 11.8))
            p.addQuadCurve(to: P(144, 32), control: P(143, 23.5))
            p.addQuadCurve(to: P(151, 44), control: P(155.2, 34.7))
            p.addQuadCurve(to: P(155, 58), control: P(163.3, 49.6))
            p.addQuadCurve(to: P(154, 71), control: P(160.9, 65.3))
            p.addQuadCurve(to: P(149, 82), control: P(159.4, 79.3))
            p.addQuadCurve(to: P(146, 81), control: P(156.8, 86.1))
            p.addQuadCurve(to: P(138, 85), control: P(147.5, 86.3))
            p.addQuadCurve(to: P(128, 79), control: P(139.8, 86.9))
            p.addQuadCurve(to: P(119, 82), control: P(131, 87.7))
            p.addQuadCurve(to: P(110, 74), control: P(118.3, 83.2))
            p.addQuadCurve(to: P(101, 77), control: P(108, 83.5))
            p.addQuadCurve(to: P(92, 70), control: P(94.2, 83.6))
            p.addQuadCurve(to: P(83, 73), control: P(83.2, 76.2))
            p.addQuadCurve(to: P(74, 68), control: P(71.2, 74.7))
            p.addQuadCurve(to: P(65, 72), control: P(59.8, 73.8))
            p.addQuadCurve(to: P(57, 74), control: P(55, 75.3))
            p.addQuadCurve(to: P(51, 82), control: P(46.3, 81.3))
            p.closeSubpath()
        }
    }
    static var lockenGlanz: [Path] {
        [
        Path { p in
            p.move(to: P(60, 44))
            p.addQuadCurve(to: P(74, 38), control: P(66, 36))
        },
        Path { p in
            p.move(to: P(84, 28))
            p.addQuadCurve(to: P(100, 25), control: P(92, 22))
        },
        Path { p in
            p.move(to: P(112, 26))
            p.addQuadCurve(to: P(127, 30), control: P(121, 24))
        },
        Path { p in
            p.move(to: P(138, 42))
            p.addQuadCurve(to: P(144, 54), control: P(144, 47))
        },
        Path { p in
            p.move(to: P(70, 58))
            p.addQuadCurve(to: P(69, 68), control: P(73, 64))
        },
        Path { p in
            p.move(to: P(94, 54))
            p.addQuadCurve(to: P(95, 66), control: P(99, 60))
        },
        Path { p in
            p.move(to: P(118, 56))
            p.addQuadCurve(to: P(119, 68), control: P(123, 62))
        },
        Path { p in
            p.move(to: P(140, 62))
            p.addQuadCurve(to: P(139, 73), control: P(143, 68))
        },
        Path { p in
            p.move(to: P(78, 44))
            p.addQuadCurve(to: P(89, 41), control: P(83, 39))
        },
        Path { p in
            p.move(to: P(122, 44))
            p.addQuadCurve(to: P(132, 47), control: P(128, 42))
        },
        ]
    }
}

/// Annika, face option 3 ("Modernes Bitmoji"). Draw order and colours: FigurView `neuesGesichtAn3`.
enum GesichtAn3 {
    static var haarHinten: Path {
        Path { p in
            p.move(to: P(100, 31))
            p.addCurve(to: P(54, 62), control1: P(76, 31), control2: P(56, 40))
            p.addCurve(to: P(50, 150), control1: P(52, 90), control2: P(51, 120))
            p.addCurve(to: P(36, 232), control1: P(48, 180), control2: P(40, 205))
            p.addLine(to: P(46, 225))
            p.addLine(to: P(53, 236))
            p.addLine(to: P(62, 228))
            p.addLine(to: P(74, 234))
            p.addLine(to: P(100, 230))
            p.addLine(to: P(126, 234))
            p.addLine(to: P(138, 228))
            p.addLine(to: P(147, 236))
            p.addLine(to: P(154, 225))
            p.addLine(to: P(164, 232))
            p.addCurve(to: P(150, 150), control1: P(160, 205), control2: P(152, 180))
            p.addCurve(to: P(146, 62), control1: P(149, 120), control2: P(148, 90))
            p.addCurve(to: P(100, 31), control1: P(144, 40), control2: P(124, 31))
            p.closeSubpath()
        }
    }
    static var hals: Path {
        Path { p in
            p.move(to: P(90.5, 126))
            p.addLine(to: P(89.5, 176))
            p.addLine(to: P(110.5, 176))
            p.addLine(to: P(109.5, 126))
            p.closeSubpath()
        }
    }
    static var halsSchatten: Path {
        Path { p in
            p.move(to: P(84, 126))
            p.addLine(to: P(116, 126))
            p.addLine(to: P(116, 140))
            p.addQuadCurve(to: P(84, 140), control: P(100, 158))
            p.closeSubpath()
        }
    }
    static var ohr: Path {
        Path { p in
            p.move(to: P(140, 97))
            p.addCurve(to: P(149, 111), control1: P(147, 93), control2: P(151, 103))
            p.addCurve(to: P(140, 118), control1: P(148, 118), control2: P(144, 121))
            p.closeSubpath()
        }
    }
    static var ohrInnen: Path {
        Path { p in
            p.move(to: P(142, 101))
            p.addCurve(to: P(142, 113), control1: P(146, 103), control2: P(146, 110))
        }
    }
    static var gesicht: Path {
        Path { p in
            p.move(to: P(100, 34))
            p.addCurve(to: P(141, 82), control1: P(123, 34), control2: P(141, 50))
            p.addCurve(to: P(128, 131), control1: P(141, 104), control2: P(137, 120))
            p.addCurve(to: P(100, 146), control1: P(119, 141), control2: P(109, 146))
            p.addCurve(to: P(72, 131), control1: P(91, 146), control2: P(81, 141))
            p.addCurve(to: P(59, 82), control1: P(63, 120), control2: P(59, 104))
            p.addCurve(to: P(100, 34), control1: P(59, 50), control2: P(77, 34))
            p.closeSubpath()
        }
    }
    static var wangeL: Path {
        oval(P(73, 119), 11, 7)
    }
    static var wangeR: Path {
        oval(P(127, 119), 11, 7)
    }
    static var augeWeissL: Path {
        Path { p in
            p.move(to: P(89.5, 103))
            p.addCurve(to: P(71.5, 98.6), control1: P(86.5, 96), control2: P(77.5, 94.5))
            p.addQuadCurve(to: P(89.5, 103), control: P(79.5, 109.5))
            p.closeSubpath()
        }
    }
    static var lidStrichL: Path {
        Path { p in
            p.move(to: P(89.5, 103))
            p.addCurve(to: P(71.5, 98.6), control1: P(86.5, 96), control2: P(77.5, 94.5))
            p.addLine(to: P(67.9, 95.8))
        }
    }
    static var fluegelL: Path {
        Path { p in
            p.move(to: P(74, 97.4))
            p.addLine(to: P(71.3, 94.6))
        }
    }
    static var augeWeissR: Path {
        Path { p in
            p.move(to: P(110.5, 103))
            p.addCurve(to: P(128.5, 98.6), control1: P(113.5, 96), control2: P(122.5, 94.5))
            p.addQuadCurve(to: P(110.5, 103), control: P(120.5, 109.5))
            p.closeSubpath()
        }
    }
    static var lidStrichR: Path {
        Path { p in
            p.move(to: P(110.5, 103))
            p.addCurve(to: P(128.5, 98.6), control1: P(113.5, 96), control2: P(122.5, 94.5))
            p.addLine(to: P(132.1, 95.8))
        }
    }
    static var fluegelR: Path {
        Path { p in
            p.move(to: P(126, 97.4))
            p.addLine(to: P(128.7, 94.6))
        }
    }
    static var lachLidL: Path {
        Path { p in
            p.move(to: P(70, 107.5))
            p.addQuadCurve(to: P(93, 106.5), control: P(81.5, 101))
            p.addLine(to: P(93, 116))
            p.addLine(to: P(70, 116))
            p.closeSubpath()
        }
    }
    static var lachLidStrichL: Path {
        Path { p in
            p.move(to: P(73, 106.5))
            p.addQuadCurve(to: P(90, 106), control: P(81.5, 102))
        }
    }
    static var lachLidR: Path {
        Path { p in
            p.move(to: P(107, 107.5))
            p.addQuadCurve(to: P(130, 106.5), control: P(118.5, 101))
            p.addLine(to: P(130, 116))
            p.addLine(to: P(107, 116))
            p.closeSubpath()
        }
    }
    static var lachLidStrichR: Path {
        Path { p in
            p.move(to: P(110, 106.5))
            p.addQuadCurve(to: P(127, 106), control: P(118.5, 102))
        }
    }
    static var braueL: Path {
        Path { p in
            p.move(to: P(91.5, 90))
            p.addQuadCurve(to: P(71.5, 87.2), control: P(81, 83.2))
            p.addQuadCurve(to: P(91, 92.4), control: P(81, 86))
            p.closeSubpath()
        }
    }
    static var braueR: Path {
        Path { p in
            p.move(to: P(108.5, 90))
            p.addQuadCurve(to: P(128.5, 87.2), control: P(119, 83.2))
            p.addQuadCurve(to: P(109, 92.4), control: P(119, 86))
            p.closeSubpath()
        }
    }
    static var nase: Path {
        Path { p in
            p.move(to: P(101.5, 112))
            p.addQuadCurve(to: P(100.5, 119.5), control: P(104, 118))
        }
    }
    static var lippeOben: Path {
        Path { p in
            p.move(to: P(92.5, 130.6))
            p.addQuadCurve(to: P(100, 129.2), control: P(96, 127.8))
            p.addQuadCurve(to: P(107.5, 130.6), control: P(104, 127.8))
            p.addQuadCurve(to: P(92.5, 130.6), control: P(100, 131.6))
            p.closeSubpath()
        }
    }
    static var lippeUnten: Path {
        Path { p in
            p.move(to: P(92.5, 130.6))
            p.addQuadCurve(to: P(107.5, 130.6), control: P(100, 131.6))
            p.addQuadCurve(to: P(100, 135.8), control: P(105, 135.8))
            p.addQuadCurve(to: P(92.5, 130.6), control: P(95, 135.8))
            p.closeSubpath()
        }
    }
    static var lippenLinie: Path {
        Path { p in
            p.move(to: P(93, 130.6))
            p.addQuadCurve(to: P(107, 130.6), control: P(100, 131.8))
        }
    }
    static var lippenGlanz: Path {
        oval(P(101.2, 133.4), 3, 0.9)
    }
    static var lachLippeOben: Path {
        Path { p in
            p.move(to: P(92, 129.5))
            p.addQuadCurve(to: P(100, 128.6), control: P(96, 127.4))
            p.addQuadCurve(to: P(108, 129.5), control: P(104, 127.4))
            p.addQuadCurve(to: P(92, 129.5), control: P(100, 132.8))
            p.closeSubpath()
        }
    }
    static var lachLippeUnten: Path {
        Path { p in
            p.move(to: P(92, 129.5))
            p.addQuadCurve(to: P(108, 129.5), control: P(100, 132.8))
            p.addQuadCurve(to: P(100, 135.6), control: P(105.5, 135.6))
            p.addQuadCurve(to: P(92, 129.5), control: P(94.5, 135.6))
            p.closeSubpath()
        }
    }
    static var lachLinie: Path {
        Path { p in
            p.move(to: P(91.5, 129.3))
            p.addQuadCurve(to: P(108.5, 129.3), control: P(100, 133.4))
        }
    }
    static var lachWinkelL: Path {
        Path { p in
            p.move(to: P(90.5, 128))
            p.addQuadCurve(to: P(92.2, 129.8), control: P(91, 129.5))
        }
    }
    static var lachWinkelR: Path {
        Path { p in
            p.move(to: P(109.5, 128))
            p.addQuadCurve(to: P(107.8, 129.8), control: P(109, 129.5))
        }
    }
    static var straehne: Path {
        Path { p in
            p.move(to: P(58.5, 70))
            p.addCurve(to: P(65, 142), control1: P(57.5, 96), control2: P(62.5, 118))
            p.addCurve(to: P(64, 76), control1: P(68, 116), control2: P(65, 100))
            p.closeSubpath()
        }
    }
    static var haarVornL: Path {
        Path { p in
            p.move(to: P(99.2, 30))
            p.addCurve(to: P(52, 60), control1: P(72, 27), control2: P(54, 38))
            p.addCurve(to: P(51, 140), control1: P(50, 84), control2: P(53, 112))
            p.addCurve(to: P(38, 230), control1: P(48, 168), control2: P(40, 198))
            p.addLine(to: P(43, 222))
            p.addLine(to: P(47, 234))
            p.addLine(to: P(52, 222))
            p.addLine(to: P(58, 231))
            p.addCurve(to: P(64, 142), control1: P(59, 200), control2: P(61, 170))
            p.addCurve(to: P(64, 102), control1: P(66, 128), control2: P(63, 114))
            p.addCurve(to: P(86, 63), control1: P(65, 86), control2: P(75, 71))
            p.addCurve(to: P(99.2, 59.5), control1: P(92, 60.5), control2: P(97, 59.5))
            p.closeSubpath()
        }
    }
    static var haarVornR: Path {
        Path { p in
            p.move(to: P(100.8, 30))
            p.addCurve(to: P(148, 60), control1: P(128, 27), control2: P(146, 38))
            p.addCurve(to: P(153, 152), control1: P(150, 86), control2: P(151, 122))
            p.addLine(to: P(150, 154))
            p.addCurve(to: P(148, 108), control1: P(149, 134), control2: P(149, 120))
            p.addCurve(to: P(114, 63), control1: P(146, 90), control2: P(128, 70))
            p.addCurve(to: P(100.8, 59.5), control1: P(108, 60.5), control2: P(103, 59.5))
            p.closeSubpath()
        }
    }
    static var haarLinien: [Path] {
        [
        Path { p in
            p.move(to: P(94, 35))
            p.addCurve(to: P(54, 92), control1: P(72, 37), control2: P(56, 56))
            p.addCurve(to: P(56, 214), control1: P(52, 130), control2: P(53, 170))
        },
        Path { p in
            p.move(to: P(86, 35))
            p.addCurve(to: P(50, 80), control1: P(66, 37), control2: P(52, 52))
        },
        Path { p in
            p.move(to: P(60, 120))
            p.addCurve(to: P(60, 222), control1: P(59, 150), control2: P(57, 180))
        },
        Path { p in
            p.move(to: P(96, 40))
            p.addCurve(to: P(67, 78), control1: P(82, 44), control2: P(72, 58))
        },
        ]
    }
    static var haarGlanz: [Path] {
        [
        Path { p in
            p.move(to: P(94, 38))
            p.addQuadCurve(to: P(63, 56), control: P(74, 39))
        },
        Path { p in
            p.move(to: P(106, 38))
            p.addQuadCurve(to: P(137, 56), control: P(126, 39))
        },
        Path { p in
            p.move(to: P(56, 150))
            p.addQuadCurve(to: P(62, 205), control: P(58, 175))
        },
        ]
    }
}
