// Generated by design/figur-redesign/swift_export.py from ahmed-B.svg and annika-3.svg. Do not edit by hand:
// change bau.py, run `python bau.py && python swift_export.py`.
// Coordinates are the 200 x 240 half-figure space of FigurView. Colours and gradients live in FigurView.

import SwiftUI

/// Ahmed, face option B ("Bitmoji modern schlank"). Draw order and colours: FigurView `neuesGesichtB`.
enum GesichtB {
    static var haarHinten: Path {
        Path { p in
            p.move(to: P(51, 86))
            p.addQuadCurve(to: P(43, 76), control: P(42.9, 82.5))
            p.addQuadCurve(to: P(40, 62), control: P(35.1, 69.8))
            p.addQuadCurve(to: P(44, 48), control: P(33.7, 54))
            p.addQuadCurve(to: P(54, 37), control: P(44.9, 40.9))
            p.addQuadCurve(to: P(68, 29), control: P(55.9, 29.2))
            p.addQuadCurve(to: P(85, 24), control: P(71.9, 19.5))
            p.addQuadCurve(to: P(102, 22), control: P(92.8, 18.7))
            p.addQuadCurve(to: P(119, 24), control: P(112.2, 16.8))
            p.addQuadCurve(to: P(134, 29), control: P(131.5, 19.8))
            p.addQuadCurve(to: P(147, 38), control: P(144.1, 31))
            p.addQuadCurve(to: P(156, 50), control: P(157.5, 41.9))
            p.addQuadCurve(to: P(160, 63), control: P(166.4, 55.7))
            p.addQuadCurve(to: P(158, 76), control: P(163.4, 70.1))
            p.addQuadCurve(to: P(150, 87), control: P(160, 83.7))
            p.addQuadCurve(to: P(151, 97), control: P(157.7, 96.3))
            p.addQuadCurve(to: P(49, 97), control: P(100, 101.4))
            p.addQuadCurve(to: P(51, 86), control: P(44.5, 94.8))
            p.closeSubpath()
        }
    }
    static var hals: Path {
        Path { p in
            p.move(to: P(88, 128))
            p.addLine(to: P(87, 176))
            p.addLine(to: P(113, 176))
            p.addLine(to: P(112, 128))
            p.closeSubpath()
        }
    }
    static var halsSchatten: Path {
        Path { p in
            p.move(to: P(80, 128))
            p.addLine(to: P(120, 128))
            p.addLine(to: P(120, 150))
            p.addQuadCurve(to: P(80, 150), control: P(100, 166))
            p.closeSubpath()
        }
    }
    static var ohrL: Path {
        Path { p in
            p.move(to: P(56, 93))
            p.addCurve(to: P(43, 107), control1: P(47, 87), control2: P(41, 97))
            p.addCurve(to: P(57, 117), control1: P(45, 116), control2: P(51, 121))
            p.closeSubpath()
        }
    }
    static var ohrR: Path {
        Path { p in
            p.move(to: P(144, 93))
            p.addCurve(to: P(157, 107), control1: P(153, 87), control2: P(159, 97))
            p.addCurve(to: P(143, 117), control1: P(155, 116), control2: P(149, 121))
            p.closeSubpath()
        }
    }
    static var ohrInnenL: Path {
        Path { p in
            p.move(to: P(52, 97))
            p.addCurve(to: P(52, 111), control1: P(47, 99), control2: P(47, 108))
        }
    }
    static var ohrInnenR: Path {
        Path { p in
            p.move(to: P(148, 97))
            p.addCurve(to: P(148, 111), control1: P(153, 99), control2: P(153, 108))
        }
    }
    static var gesicht: Path {
        Path { p in
            p.move(to: P(100, 26))
            p.addCurve(to: P(147, 77), control1: P(127, 26), control2: P(147, 44))
            p.addCurve(to: P(144, 114), control1: P(147, 95), control2: P(146, 106))
            p.addLine(to: P(137, 136))
            p.addLine(to: P(117, 153.5))
            p.addQuadCurve(to: P(83, 153.5), control: P(100, 158))
            p.addLine(to: P(63, 136))
            p.addLine(to: P(56, 114))
            p.addCurve(to: P(53, 77), control1: P(54, 106), control2: P(53, 95))
            p.addCurve(to: P(100, 26), control1: P(53, 44), control2: P(73, 26))
            p.closeSubpath()
        }
    }
    static var ponySchatten: Path {
        Path { p in
            p.move(to: P(51, 86))
            p.addQuadCurve(to: P(43, 76), control: P(39.7, 84.2))
            p.addQuadCurve(to: P(40, 62), control: P(33.6, 70.5))
            p.addQuadCurve(to: P(44, 48), control: P(34, 54.6))
            p.addQuadCurve(to: P(54, 37), control: P(41.3, 40.2))
            p.addQuadCurve(to: P(68, 29), control: P(54.3, 28.7))
            p.addQuadCurve(to: P(85, 24), control: P(71.7, 20.1))
            p.addQuadCurve(to: P(102, 22), control: P(92, 15.1))
            p.addQuadCurve(to: P(119, 24), control: P(112.8, 15.3))
            p.addQuadCurve(to: P(134, 29), control: P(131.7, 20.4))
            p.addQuadCurve(to: P(147, 38), control: P(147.3, 29.4))
            p.addQuadCurve(to: P(156, 50), control: P(159.2, 41.9))
            p.addQuadCurve(to: P(160, 63), control: P(166, 56.3))
            p.addQuadCurve(to: P(158, 76), control: P(166.9, 71))
            p.addQuadCurve(to: P(150, 87), control: P(161.3, 84.7))
            p.addQuadCurve(to: P(150, 90), control: P(156.8, 92.7))
            p.addQuadCurve(to: P(142, 92), control: P(152.5, 95.7))
            p.addQuadCurve(to: P(133, 87), control: P(143.6, 94.6))
            p.addQuadCurve(to: P(124, 91), control: P(133.9, 94.9))
            p.addQuadCurve(to: P(115, 86), control: P(123.8, 95.2))
            p.addQuadCurve(to: P(106, 91), control: P(113.1, 96.1))
            p.addQuadCurve(to: P(97, 86), control: P(101.9, 96.5))
            p.addQuadCurve(to: P(89, 91), control: P(91.2, 96.3))
            p.addQuadCurve(to: P(82, 95), control: P(82.4, 100.4))
            p.addQuadCurve(to: P(75, 89), control: P(74.2, 98.8))
            p.addQuadCurve(to: P(65, 91), control: P(64.5, 95.8))
            p.addQuadCurve(to: P(57, 89), control: P(54.8, 95.1))
            p.addQuadCurve(to: P(51, 86), control: P(47.3, 91.8))
            p.closeSubpath()
        }
    }
    static var wangeL: Path {
        oval(P(62, 122), 10, 15)
    }
    static var wangeR: Path {
        oval(P(138, 122), 10, 15)
    }
    static var taperL: Path {
        Path { p in
            p.move(to: P(47, 80))
            p.addCurve(to: P(51, 101), control1: P(46, 88), control2: P(47, 96))
            p.addLine(to: P(57, 100))
            p.addCurve(to: P(59, 81), control1: P(56, 94), control2: P(56, 87))
            p.closeSubpath()
        }
    }
    static var taperR: Path {
        Path { p in
            p.move(to: P(153, 80))
            p.addCurve(to: P(149, 101), control1: P(154, 88), control2: P(153, 96))
            p.addLine(to: P(143, 100))
            p.addCurve(to: P(141, 81), control1: P(144, 94), control2: P(144, 87))
            p.closeSubpath()
        }
    }
    static var kinnbart: Path {
        Path { p in
            p.move(to: P(96, 147))
            p.addQuadCurve(to: P(104, 147), control: P(100, 146))
            p.addQuadCurve(to: P(100, 153), control: P(103.5, 152.5))
            p.addQuadCurve(to: P(96, 147), control: P(96.5, 152.5))
            p.closeSubpath()
        }
    }
    static var kinnSchatten: Path {
        Path { p in
            p.move(to: P(86, 153))
            p.addQuadCurve(to: P(114, 153), control: P(100, 149))
            p.addLine(to: P(114, 162))
            p.addLine(to: P(86, 162))
            p.closeSubpath()
        }
    }
    static var augeWeissL: Path {
        Path { p in
            p.move(to: P(91, 102))
            p.addQuadCurve(to: P(70, 99.5), control: P(81, 88))
            p.addQuadCurve(to: P(91, 102), control: P(80, 110))
            p.closeSubpath()
        }
    }
    static var lidL: Path {
        Path { p in
            p.move(to: P(89, 92))
            p.addLine(to: P(72, 92))
            p.addLine(to: P(72, 101))
            p.addQuadCurve(to: P(89, 102.5), control: P(81, 96.5))
            p.closeSubpath()
        }
    }
    static var lidStrichL: Path {
        Path { p in
            p.move(to: P(91, 102.5))
            p.addQuadCurve(to: P(70, 101), control: P(81, 96.5))
        }
    }
    static var lidFalteL: Path {
        Path { p in
            p.move(to: P(89, 95.5))
            p.addQuadCurve(to: P(71, 96), control: P(81, 89))
        }
    }
    static var augeWeissR: Path {
        Path { p in
            p.move(to: P(109, 102))
            p.addQuadCurve(to: P(130, 99.5), control: P(119, 88))
            p.addQuadCurve(to: P(109, 102), control: P(120, 110))
            p.closeSubpath()
        }
    }
    static var lidR: Path {
        Path { p in
            p.move(to: P(107, 92))
            p.addLine(to: P(132, 92))
            p.addLine(to: P(132, 101))
            p.addQuadCurve(to: P(107, 102.5), control: P(119, 96.5))
            p.closeSubpath()
        }
    }
    static var lidStrichR: Path {
        Path { p in
            p.move(to: P(109, 102.5))
            p.addQuadCurve(to: P(130, 101), control: P(119, 96.5))
        }
    }
    static var lidFalteR: Path {
        Path { p in
            p.move(to: P(111, 95.5))
            p.addQuadCurve(to: P(129, 96), control: P(119, 89))
        }
    }
    static var lachLidL: Path {
        Path { p in
            p.move(to: P(69, 107))
            p.addQuadCurve(to: P(93, 106), control: P(81, 100))
            p.addLine(to: P(93, 115))
            p.addLine(to: P(69, 115))
            p.closeSubpath()
        }
    }
    static var lachLidStrichL: Path {
        Path { p in
            p.move(to: P(72, 106))
            p.addQuadCurve(to: P(90, 105.5), control: P(81, 101))
        }
    }
    static var lachLidR: Path {
        Path { p in
            p.move(to: P(107, 107))
            p.addQuadCurve(to: P(131, 106), control: P(119, 100))
            p.addLine(to: P(131, 115))
            p.addLine(to: P(107, 115))
            p.closeSubpath()
        }
    }
    static var lachLidStrichR: Path {
        Path { p in
            p.move(to: P(110, 106))
            p.addQuadCurve(to: P(128, 105.5), control: P(119, 101))
        }
    }
    static var braueL: Path {
        Path { p in
            p.move(to: P(92, 93.5))
            p.addQuadCurve(to: P(69, 92), control: P(81, 90.5))
        }
    }
    static var braueR: Path {
        Path { p in
            p.move(to: P(108, 93.5))
            p.addQuadCurve(to: P(131, 92), control: P(119, 90.5))
        }
    }
    static var nase: Path {
        Path { p in
            p.move(to: P(102, 101))
            p.addLine(to: P(105, 124.5))
            p.addQuadCurve(to: P(98, 128), control: P(103.5, 129))
        }
    }
    static var nasenSchatten: Path {
        oval(P(100, 129.5), 6.5, 2)
    }
    static var schnurrbart: Path {
        Path { p in
            p.move(to: P(100, 133))
            p.addCurve(to: P(80, 138), control1: P(95, 131), control2: P(87, 131.5))
            p.addCurve(to: P(100, 135.8), control1: P(87, 135), control2: P(95, 135))
            p.addCurve(to: P(120, 138), control1: P(105, 135), control2: P(113, 135))
            p.addCurve(to: P(100, 133), control1: P(113, 131.5), control2: P(105, 131))
            p.closeSubpath()
        }
    }
    static var lippeOben: Path {
        Path { p in
            p.move(to: P(90, 141))
            p.addQuadCurve(to: P(100, 139.5), control: P(95, 138.5))
            p.addQuadCurve(to: P(110, 141), control: P(105, 138.5))
            p.addQuadCurve(to: P(90, 141), control: P(100, 142.2))
            p.closeSubpath()
        }
    }
    static var lippeUnten: Path {
        Path { p in
            p.move(to: P(90, 141))
            p.addQuadCurve(to: P(110, 141), control: P(100, 142.2))
            p.addQuadCurve(to: P(100, 146), control: P(106, 146))
            p.addQuadCurve(to: P(90, 141), control: P(94, 146))
            p.closeSubpath()
        }
    }
    static var lachMund: Path {
        Path { p in
            p.move(to: P(88, 139))
            p.addQuadCurve(to: P(112, 139), control: P(100, 142.5))
            p.addQuadCurve(to: P(100, 149.5), control: P(109, 149.5))
            p.addQuadCurve(to: P(88, 139), control: P(91, 149.5))
            p.closeSubpath()
        }
    }
    static var lachZaehne: Path {
        Path { p in
            p.move(to: P(90, 140))
            p.addQuadCurve(to: P(110, 140), control: P(100, 143))
            p.addLine(to: P(109, 142.5))
            p.addQuadCurve(to: P(91, 142.5), control: P(100, 145))
            p.closeSubpath()
        }
    }
    static var lachZunge: Path {
        Path { p in
            p.move(to: P(94, 147.5))
            p.addQuadCurve(to: P(106, 147.5), control: P(100, 145))
            p.addQuadCurve(to: P(94, 147.5), control: P(100, 150))
            p.closeSubpath()
        }
    }
    static var haarVorn: Path {
        Path { p in
            p.move(to: P(51, 86))
            p.addQuadCurve(to: P(43, 76), control: P(42.2, 82.9))
            p.addQuadCurve(to: P(40, 62), control: P(34.4, 70.1))
            p.addQuadCurve(to: P(44, 48), control: P(32.8, 54.2))
            p.addQuadCurve(to: P(54, 37), control: P(44.1, 40.8))
            p.addQuadCurve(to: P(68, 29), control: P(55.1, 28.9))
            p.addQuadCurve(to: P(85, 24), control: P(71.2, 19))
            p.addQuadCurve(to: P(102, 22), control: P(92.6, 17.9))
            p.addQuadCurve(to: P(119, 24), control: P(112.5, 16.1))
            p.addQuadCurve(to: P(134, 29), control: P(132.2, 19.3))
            p.addQuadCurve(to: P(147, 38), control: P(144.9, 30.7))
            p.addQuadCurve(to: P(156, 50), control: P(158.4, 41.9))
            p.addQuadCurve(to: P(160, 63), control: P(167.2, 55.9))
            p.addQuadCurve(to: P(158, 76), control: P(164.1, 70.3))
            p.addQuadCurve(to: P(150, 87), control: P(160.7, 84.2))
            p.addQuadCurve(to: P(150, 86), control: P(158.1, 90.8))
            p.addQuadCurve(to: P(142, 88), control: P(150.5, 89.6))
            p.addQuadCurve(to: P(133, 83), control: P(143.5, 89.5))
            p.addQuadCurve(to: P(124, 87), control: P(135.4, 91.1))
            p.addQuadCurve(to: P(115, 82), control: P(122.7, 88.6))
            p.addQuadCurve(to: P(106, 87), control: P(113.3, 91.1))
            p.addQuadCurve(to: P(97, 82), control: P(102.1, 93.7))
            p.addQuadCurve(to: P(89, 87), control: P(91.6, 89.5))
            p.addQuadCurve(to: P(82, 91), control: P(82.3, 95.4))
            p.addQuadCurve(to: P(75, 85), control: P(72.9, 95.3))
            p.addQuadCurve(to: P(65, 87), control: P(66.1, 89.4))
            p.addQuadCurve(to: P(57, 85), control: P(55, 90))
            p.addQuadCurve(to: P(51, 86), control: P(46, 90))
            p.closeSubpath()
        }
    }
    static var lockenGlanz: [Path] {
        [
        Path { p in
            p.move(to: P(56, 50))
            p.addQuadCurve(to: P(71, 43), control: P(63, 42))
        },
        Path { p in
            p.move(to: P(82, 34))
            p.addQuadCurve(to: P(98, 31), control: P(90, 28))
        },
        Path { p in
            p.move(to: P(112, 32))
            p.addQuadCurve(to: P(127, 36), control: P(121, 30))
        },
        Path { p in
            p.move(to: P(140, 46))
            p.addQuadCurve(to: P(146, 58), control: P(146, 51))
        },
        Path { p in
            p.move(to: P(66, 66))
            p.addQuadCurve(to: P(65, 78), control: P(70, 73))
        },
        Path { p in
            p.move(to: P(92, 62))
            p.addQuadCurve(to: P(93, 75), control: P(97, 69))
        },
        Path { p in
            p.move(to: P(118, 64))
            p.addQuadCurve(to: P(119, 76), control: P(123, 70))
        },
        Path { p in
            p.move(to: P(142, 68))
            p.addQuadCurve(to: P(141, 79), control: P(145, 74))
        },
        Path { p in
            p.move(to: P(76, 50))
            p.addQuadCurve(to: P(87, 47), control: P(81, 45))
        },
        Path { p in
            p.move(to: P(124, 50))
            p.addQuadCurve(to: P(134, 53), control: P(130, 48))
        },
        ]
    }
}

/// Annika, face option 3 ("Modernes Bitmoji"). Draw order and colours: FigurView `neuesGesichtAn3`.
enum GesichtAn3 {
    static var haarHinten: Path {
        Path { p in
            p.move(to: P(100, 31))
            p.addCurve(to: P(54, 62), control1: P(76, 31), control2: P(56, 40))
            p.addCurve(to: P(50, 150), control1: P(52, 90), control2: P(51, 120))
            p.addCurve(to: P(36, 232), control1: P(48, 180), control2: P(40, 205))
            p.addLine(to: P(46, 225))
            p.addLine(to: P(53, 236))
            p.addLine(to: P(62, 228))
            p.addLine(to: P(74, 234))
            p.addLine(to: P(100, 230))
            p.addLine(to: P(126, 234))
            p.addLine(to: P(138, 228))
            p.addLine(to: P(147, 236))
            p.addLine(to: P(154, 225))
            p.addLine(to: P(164, 232))
            p.addCurve(to: P(150, 150), control1: P(160, 205), control2: P(152, 180))
            p.addCurve(to: P(146, 62), control1: P(149, 120), control2: P(148, 90))
            p.addCurve(to: P(100, 31), control1: P(144, 40), control2: P(124, 31))
            p.closeSubpath()
        }
    }
    static var hals: Path {
        Path { p in
            p.move(to: P(90.5, 126))
            p.addLine(to: P(89.5, 176))
            p.addLine(to: P(110.5, 176))
            p.addLine(to: P(109.5, 126))
            p.closeSubpath()
        }
    }
    static var halsSchatten: Path {
        Path { p in
            p.move(to: P(84, 126))
            p.addLine(to: P(116, 126))
            p.addLine(to: P(116, 140))
            p.addQuadCurve(to: P(84, 140), control: P(100, 158))
            p.closeSubpath()
        }
    }
    static var ohr: Path {
        Path { p in
            p.move(to: P(140, 97))
            p.addCurve(to: P(149, 111), control1: P(147, 93), control2: P(151, 103))
            p.addCurve(to: P(140, 118), control1: P(148, 118), control2: P(144, 121))
            p.closeSubpath()
        }
    }
    static var ohrInnen: Path {
        Path { p in
            p.move(to: P(142, 101))
            p.addCurve(to: P(142, 113), control1: P(146, 103), control2: P(146, 110))
        }
    }
    static var gesicht: Path {
        Path { p in
            p.move(to: P(100, 34))
            p.addCurve(to: P(141, 82), control1: P(123, 34), control2: P(141, 50))
            p.addCurve(to: P(128, 131), control1: P(141, 104), control2: P(137, 120))
            p.addCurve(to: P(100, 146), control1: P(119, 141), control2: P(109, 146))
            p.addCurve(to: P(72, 131), control1: P(91, 146), control2: P(81, 141))
            p.addCurve(to: P(59, 82), control1: P(63, 120), control2: P(59, 104))
            p.addCurve(to: P(100, 34), control1: P(59, 50), control2: P(77, 34))
            p.closeSubpath()
        }
    }
    static var wangeL: Path {
        oval(P(73, 119), 11, 7)
    }
    static var wangeR: Path {
        oval(P(127, 119), 11, 7)
    }
    static var augeWeissL: Path {
        Path { p in
            p.move(to: P(89.5, 103))
            p.addCurve(to: P(71.5, 98.6), control1: P(86.5, 96), control2: P(77.5, 94.5))
            p.addQuadCurve(to: P(89.5, 103), control: P(79.5, 109.5))
            p.closeSubpath()
        }
    }
    static var lidStrichL: Path {
        Path { p in
            p.move(to: P(89.5, 103))
            p.addCurve(to: P(71.5, 98.6), control1: P(86.5, 96), control2: P(77.5, 94.5))
            p.addLine(to: P(67.9, 95.8))
        }
    }
    static var fluegelL: Path {
        Path { p in
            p.move(to: P(74, 97.4))
            p.addLine(to: P(71.3, 94.6))
        }
    }
    static var augeWeissR: Path {
        Path { p in
            p.move(to: P(110.5, 103))
            p.addCurve(to: P(128.5, 98.6), control1: P(113.5, 96), control2: P(122.5, 94.5))
            p.addQuadCurve(to: P(110.5, 103), control: P(120.5, 109.5))
            p.closeSubpath()
        }
    }
    static var lidStrichR: Path {
        Path { p in
            p.move(to: P(110.5, 103))
            p.addCurve(to: P(128.5, 98.6), control1: P(113.5, 96), control2: P(122.5, 94.5))
            p.addLine(to: P(132.1, 95.8))
        }
    }
    static var fluegelR: Path {
        Path { p in
            p.move(to: P(126, 97.4))
            p.addLine(to: P(128.7, 94.6))
        }
    }
    static var lachLidL: Path {
        Path { p in
            p.move(to: P(70, 107.5))
            p.addQuadCurve(to: P(93, 106.5), control: P(81.5, 101))
            p.addLine(to: P(93, 116))
            p.addLine(to: P(70, 116))
            p.closeSubpath()
        }
    }
    static var lachLidStrichL: Path {
        Path { p in
            p.move(to: P(73, 106.5))
            p.addQuadCurve(to: P(90, 106), control: P(81.5, 102))
        }
    }
    static var lachLidR: Path {
        Path { p in
            p.move(to: P(107, 107.5))
            p.addQuadCurve(to: P(130, 106.5), control: P(118.5, 101))
            p.addLine(to: P(130, 116))
            p.addLine(to: P(107, 116))
            p.closeSubpath()
        }
    }
    static var lachLidStrichR: Path {
        Path { p in
            p.move(to: P(110, 106.5))
            p.addQuadCurve(to: P(127, 106), control: P(118.5, 102))
        }
    }
    static var braueL: Path {
        Path { p in
            p.move(to: P(91.5, 90))
            p.addQuadCurve(to: P(71.5, 87.2), control: P(81, 83.2))
            p.addQuadCurve(to: P(91, 92.4), control: P(81, 86))
            p.closeSubpath()
        }
    }
    static var braueR: Path {
        Path { p in
            p.move(to: P(108.5, 90))
            p.addQuadCurve(to: P(128.5, 87.2), control: P(119, 83.2))
            p.addQuadCurve(to: P(109, 92.4), control: P(119, 86))
            p.closeSubpath()
        }
    }
    static var nase: Path {
        Path { p in
            p.move(to: P(101.5, 112))
            p.addQuadCurve(to: P(100.5, 119.5), control: P(104, 118))
        }
    }
    static var lippeOben: Path {
        Path { p in
            p.move(to: P(92.5, 130.6))
            p.addQuadCurve(to: P(100, 129.2), control: P(96, 127.8))
            p.addQuadCurve(to: P(107.5, 130.6), control: P(104, 127.8))
            p.addQuadCurve(to: P(92.5, 130.6), control: P(100, 131.6))
            p.closeSubpath()
        }
    }
    static var lippeUnten: Path {
        Path { p in
            p.move(to: P(92.5, 130.6))
            p.addQuadCurve(to: P(107.5, 130.6), control: P(100, 131.6))
            p.addQuadCurve(to: P(100, 135.8), control: P(105, 135.8))
            p.addQuadCurve(to: P(92.5, 130.6), control: P(95, 135.8))
            p.closeSubpath()
        }
    }
    static var lippenLinie: Path {
        Path { p in
            p.move(to: P(93, 130.6))
            p.addQuadCurve(to: P(107, 130.6), control: P(100, 131.8))
        }
    }
    static var lippenGlanz: Path {
        oval(P(101.2, 133.4), 3, 0.9)
    }
    static var lachLippeOben: Path {
        Path { p in
            p.move(to: P(92, 129.5))
            p.addQuadCurve(to: P(100, 128.6), control: P(96, 127.4))
            p.addQuadCurve(to: P(108, 129.5), control: P(104, 127.4))
            p.addQuadCurve(to: P(92, 129.5), control: P(100, 132.8))
            p.closeSubpath()
        }
    }
    static var lachLippeUnten: Path {
        Path { p in
            p.move(to: P(92, 129.5))
            p.addQuadCurve(to: P(108, 129.5), control: P(100, 132.8))
            p.addQuadCurve(to: P(100, 135.6), control: P(105.5, 135.6))
            p.addQuadCurve(to: P(92, 129.5), control: P(94.5, 135.6))
            p.closeSubpath()
        }
    }
    static var lachLinie: Path {
        Path { p in
            p.move(to: P(91.5, 129.3))
            p.addQuadCurve(to: P(108.5, 129.3), control: P(100, 133.4))
        }
    }
    static var lachWinkelL: Path {
        Path { p in
            p.move(to: P(90.5, 128))
            p.addQuadCurve(to: P(92.2, 129.8), control: P(91, 129.5))
        }
    }
    static var lachWinkelR: Path {
        Path { p in
            p.move(to: P(109.5, 128))
            p.addQuadCurve(to: P(107.8, 129.8), control: P(109, 129.5))
        }
    }
    static var straehne: Path {
        Path { p in
            p.move(to: P(58.5, 70))
            p.addCurve(to: P(65, 142), control1: P(57.5, 96), control2: P(62.5, 118))
            p.addCurve(to: P(64, 76), control1: P(68, 116), control2: P(65, 100))
            p.closeSubpath()
        }
    }
    static var haarVornL: Path {
        Path { p in
            p.move(to: P(99.2, 30))
            p.addCurve(to: P(52, 60), control1: P(72, 27), control2: P(54, 38))
            p.addCurve(to: P(51, 140), control1: P(50, 84), control2: P(53, 112))
            p.addCurve(to: P(38, 230), control1: P(48, 168), control2: P(40, 198))
            p.addLine(to: P(43, 222))
            p.addLine(to: P(47, 234))
            p.addLine(to: P(52, 222))
            p.addLine(to: P(58, 231))
            p.addCurve(to: P(64, 142), control1: P(59, 200), control2: P(61, 170))
            p.addCurve(to: P(64, 102), control1: P(66, 128), control2: P(63, 114))
            p.addCurve(to: P(86, 68.5), control1: P(65, 86), control2: P(75, 74.3))
            p.addCurve(to: P(99.2, 65), control1: P(92, 66), control2: P(97, 65))
            p.closeSubpath()
        }
    }
    static var haarVornR: Path {
        Path { p in
            p.move(to: P(100.8, 30))
            p.addCurve(to: P(148, 60), control1: P(128, 27), control2: P(146, 38))
            p.addCurve(to: P(153, 152), control1: P(150, 86), control2: P(151, 122))
            p.addCurve(to: P(162, 230), control1: P(156, 176), control2: P(160, 200))
            p.addLine(to: P(157, 222))
            p.addLine(to: P(153, 234))
            p.addLine(to: P(148, 222))
            p.addLine(to: P(143, 231))
            p.addCurve(to: P(147, 158), control1: P(143, 206), control2: P(145, 180))
            p.addLine(to: P(150, 154))
            p.addCurve(to: P(148, 108), control1: P(149, 134), control2: P(149, 120))
            p.addCurve(to: P(114, 68.5), control1: P(146, 90), control2: P(128, 73.3))
            p.addCurve(to: P(100.8, 65), control1: P(108, 66), control2: P(103, 65))
            p.closeSubpath()
        }
    }
    static var haarLinien: [Path] {
        [
        Path { p in
            p.move(to: P(94, 35))
            p.addCurve(to: P(54, 92), control1: P(72, 37), control2: P(56, 56))
            p.addCurve(to: P(56, 214), control1: P(52, 130), control2: P(53, 170))
        },
        Path { p in
            p.move(to: P(86, 35))
            p.addCurve(to: P(50, 80), control1: P(66, 37), control2: P(52, 52))
        },
        Path { p in
            p.move(to: P(60, 120))
            p.addCurve(to: P(60, 222), control1: P(59, 150), control2: P(57, 180))
        },
        Path { p in
            p.move(to: P(96, 40))
            p.addCurve(to: P(67, 78), control1: P(82, 44), control2: P(72, 58))
        },
        ]
    }
    static var haarGlanz: [Path] {
        [
        Path { p in
            p.move(to: P(94, 38))
            p.addQuadCurve(to: P(63, 56), control: P(74, 39))
        },
        Path { p in
            p.move(to: P(106, 38))
            p.addQuadCurve(to: P(137, 56), control: P(126, 39))
        },
        Path { p in
            p.move(to: P(56, 150))
            p.addQuadCurve(to: P(62, 205), control: P(58, 175))
        },
        ]
    }
}
